# If you are a trusted developer and want to use our standard developer keys, the only credentials that need to be set
# here are the credentials for parameter store.  If you are a new developer to the project, you will need at Mail, S3,
# and Cloudfront credentials for full site functionality.  If you are using a local version of XNAT running through a
# virtual machine and have not changed the default credentials, nothing needs to be set here.


PARAMETER_STORE:
  KEY_ID:
  SECRET_KEY:


MIND_XNAT:
  XNAT_USER:
  XNAT_PASSWORD:


BACKUP_XNAT:
  XNAT_USER:
  XNAT_PASSWORD:


CLOUDFRONT:
  KEY_ID:
  SECRET_KEY:

S3:
  KEY_ID:
  SECRET_KEY:

MAIL:
  MAIL_USERNAME:
  MAIL_PASSWORD:

Semaphore:
  AUTH_TOKEN:


