version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - /usr/src/app/flask_brain_db/static
   command: /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app
   depends_on:
     - mysql
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
 
 data:
   image: mysql:5.7
   volumes:
     - /var/lib/mysql
   command: "true"
 
 mysql:
   restart: always
   build: ./mysql
   volumes_from:
     - data
   ports:
     - "3307:3307"
