version: '3'
 
services:
 web:
   restart: always
   build: ./web
   volumes:
     - user-data:/usr/src/app/flask_brain_db/static/images/data
     - /etc/letsencrypt:/etc/letsencrypt
   command: bash -c "sleep 10 && python manage.py db upgrade && /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app"
   depends_on:
     - jatos
   
 jatos:
   restart: always
   build: ./jatos
   expose:
    - "9000"
   depends_on:
    - mysql  
   volumes:
    - jatos-data:/opt/docker
   environment:
       JATOS_DB_URL: "jdbc:mysql://mysql/brain_db?characterEncoding=UTF-8&useSSL=false"
       JATOS_DB_USERNAME: "mbam"
       JATOS_DB_PASSWORD: "mbam123"
       JATOS_DB_DRIVER: "com.mysql.jdbc.Driver"
       JATOS_JPA: "mysqlPersistenceUnit"

 nginx:
   restart: always
   build:
     context: ./nginx
     args:
       - NGINX_CONFIG_FILE=${NGINX_CONFIG_FILE}
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./web/flask_brain_db/static:/usr/src/app/flask_brain_db/static
     - user-data:/usr/src/app/flask_brain_db/static/images/data
     - /etc/letsencrypt:/etc/letsencrypt
   depends_on:
     - web
 
 mysql:
   restart: always
   build: ./mysql
   volumes:
     - mysql-data:/var/lib/mysql
   ports:
     - "3306:3306"
   environment:
       MYSQL_DATABASE: "brain_db"
       MYSQL_ROOT_PASSWORD: "test"
       MYSQL_USER: "mbam"
       MYSQL_PASSWORD: "mbam123"

volumes:
  jatos-data:
  user-data:
  mysql-data:
