version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - /usr/src/app/flask_brain_db/static
   command: /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app
   depends_on:
     - mysql
   
 jatos:
   restart: always
   build: ./jatos
   expose:
    - "9000"
   depends_on:
    - mysql   
   environment:
       JATOS_DB_URL: "jdbc:mysql://mysql/brain_db?characterEncoding=UTF-8"
       JATOS_DB_USERNAME: "mbam"
       JATOS_DB_PASSWORD: "mbam123"
       JATOS_DB_DRIVER: "com.mysql.jdbc.Driver"
       JATOS_JPA: "mysqlPersistenceUnit"

 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
 
 mysql:
   container_name: mbam_mysql
   restart: always
   image: mysql:5.7
   build: ./mysql
   volumes:
     - data:/var/lib/mysql
   ports:
     - "3306:3306"
   environment:
       MYSQL_DATABASE: "brain_db"
       MYSQL_ROOT_PASSWORD: "test"
       MYSQL_USER: "mbam"
       MYSQL_PASSWORD: "mbam123"

volumes:
   data:
