version: '3'

services:
  jatos:
    depends_on:
      - mysql 

  mysql:
   restart: always
   build: ./mysql
   volumes:
     - mysql-data:/var/lib/mysql
   ports:
     - "3306:3306"
   environment:
       MYSQL_DATABASE: "brain_db"
       MYSQL_ROOT_PASSWORD: "test"
       MYSQL_USER: "mbam"
       MYSQL_PASSWORD: "mbam123"
   healthcheck:
       test: /etc/init.d/mysql status
       interval: 3s
       timeout: 6s
       retries: 30

volumes:
  mysql-data:
