version: '3'

services:
 web:
   restart: always
   build: ./web
   environment:
     - "PYTHONUNBUFFERED=1"
   env_file:
     - app_config.env
   volumes:
     - user-data:/usr/src/app/flask_brain_db/static/images/data
   command: bash -c "sleep 20 && python manage.py db upgrade && /usr/local/bin/gunicorn -w 1 -b :8000 wsgi:app"
   depends_on:
     - jatos

 jatos:
   restart: always
   build: ./jatos
   expose:
    - "9000"
   volumes:
    - jatos-data:/opt/docker
   env_file:
     - jatos_config.env

 nginx:
   restart: always
   build:
     context: ./nginx
     args:
       - NGINX_CONFIG_FILE=${NGINX_CONFIG_FILE}
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./web/flask_brain_db/static:/usr/src/app/flask_brain_db/static
     - user-data:/usr/src/app/flask_brain_db/static/images/data
   depends_on:
     - web

volumes:
  jatos-data:
  user-data:
