version: '3'
 
services:
 web:
   restart: always
   build: ./web
   volumes:
     - web-static:/usr/src/app/flask_brain_db/static
     - ssl-cert:/etc/letsencrypt
   command: bash -c "sleep 10 && python manage.py db upgrade && /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app"
   depends_on:
     - jatos
   
 jatos:
   restart: always
   build: ./jatos
   expose:
    - "9000"
   depends_on:
    - mysql   
   environment:
       JATOS_DB_URL: "jdbc:mysql://mysql/brain_db?characterEncoding=UTF-8"
       JATOS_DB_USERNAME: "mbam"
       JATOS_DB_PASSWORD: "mbam123"
       JATOS_DB_DRIVER: "com.mysql.jdbc.Driver"
       JATOS_JPA: "mysqlPersistenceUnit"

 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - /www/static
     - /www/public
     - web-static
     - ssl-cert
   depends_on:
     - web
 
 mysql:
   restart: always
   build: ./mysql
   volumes:
       # Below will map named volume to container path
     - mysql-data:/var/lib/mysql
   ports:
     - "3306:3306"
   environment:
       MYSQL_DATABASE: "brain_db"
       MYSQL_ROOT_PASSWORD: "test"
       MYSQL_USER: "mbam"
       MYSQL_PASSWORD: "mbam123"
       
volumes:
  # Below will map local path (/var/lib/mysql) to docker volume
  mysql-data:/var/lib/mysql
  ssl-cert:/etc/letsencrypt
  web-static:./web/flask_brain_db/static
   
   

