version: '3'

services:
 web:
   restart: always
   build: ./cookiecutter_mbam
   environment:
     - "PYTHONUNBUFFERED=1"
   volumes:
     - user-data:/app/cookiecutter_mbam/static/files
     - assets-data:/app/cookiecutter_mbam/static/build
   command: bash -c "sleep 20 && cp .docker_env .env && npm run build && flask run"
   depends_on:
     - jatos

 jatos:
   restart: always
   build: ./jatos
   expose:
    - "9000"
   volumes:
    - jatos-data:/opt/docker
   env_file:
     - jatos_config.env


 nginx:
   restart: always
   build:
     context: ./nginx
     args:
       - NGINX_CONFIG_FILE=${NGINX_CONFIG_FILE}
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - user-data:/app/cookiecutter_mbam/static/files
     - assets-data:/app/cookiecutter_mbam/static/build
   depends_on:
     - web

volumes:
  jatos-data:
  user-data:
  assets-data:
