"""empty message

Revision ID: 7952585dcd87
Revises: 5a849d66ade5
Create Date: 2019-04-29 08:38:56.175026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7952585dcd87'
down_revision = '5a849d66ade5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('xnat_container_id', sa.String(length=80), nullable=True),
    sa.Column('xnat_uri', sa.String(length=255), nullable=True),
    sa.Column('cloud_storage_key', sa.String(length=255), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_storage_key'),
    sa.UniqueConstraint('xnat_uri')
    )
    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_strength', sa.String(length=80), nullable=True))

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aws_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('nifti_aws_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('orig_aws_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('xnat_status', sa.String(length=80), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assented', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parent_email', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('parent_email')
        batch_op.drop_column('assented')

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('xnat_status')
        batch_op.drop_column('orig_aws_key')
        batch_op.drop_column('nifti_aws_key')
        batch_op.drop_column('aws_status')

    with op.batch_alter_table('experiment', schema=None) as batch_op:
        batch_op.drop_column('field_strength')

    op.drop_table('derivation')
    # ### end Alembic commands ###
