"""empty message

Revision ID: 7dc4d40ca6e8
Revises: ebd409458a2c
Create Date: 2020-04-15 21:06:37.752129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc4d40ca6e8'
down_revision = 'ebd409458a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('visible', sa.Boolean(), nullable=True))
    op.add_column('scan', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'visible')
    op.drop_column('experiment', 'visible')
    # ### end Alembic commands ###
