"""empty message
Revision ID: 8c187f0b5a59
Revises: a85058a4a8ae
Create Date: 2019-09-28 15:38:51.867797
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c187f0b5a59'
down_revision = 'a85058a4a8ae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scan', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan', type_='foreignkey')
    op.drop_column('scan', 'user_id')
    # ### end Alembic commands ###
