"""empty message

Revision ID: a167f6258645
Revises: a85058a4a8ae
Create Date: 2019-11-11 20:11:47.974568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a167f6258645'
down_revision = 'a85058a4a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('derivation', sa.Column('aws_key', sa.String(length=255), nullable=True))
    op.add_column('derivation', sa.Column('aws_status', sa.String(length=255), nullable=False))
    op.add_column('derivation', sa.Column('container_status', sa.String(length=255), nullable=False))
    op.add_column('derivation', sa.Column('cs_id', sa.String(length=80), nullable=True))
    op.add_column('derivation', sa.Column('xnat_host', sa.String(length=255), nullable=True))
    op.drop_index('cloud_storage_key', table_name='derivation')
    op.create_unique_constraint(None, 'derivation', ['aws_key'])
    op.drop_column('derivation', 'status')
    op.drop_column('derivation', 'cloud_storage_key')
    op.add_column('scan', sa.Column('aws_key', sa.String(length=255), nullable=True))
    op.drop_column('scan', 'xnat_label')
    op.drop_column('scan', 'orig_aws_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('orig_aws_key', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('scan', sa.Column('xnat_label', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('scan', 'aws_key')
    op.add_column('derivation', sa.Column('cloud_storage_key', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('derivation', sa.Column('status', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'derivation', type_='unique')
    op.create_index('cloud_storage_key', 'derivation', ['cloud_storage_key'], unique=True)
    op.drop_column('derivation', 'xnat_host')
    op.drop_column('derivation', 'cs_id')
    op.drop_column('derivation', 'container_status')
    op.drop_column('derivation', 'aws_status')
    op.drop_column('derivation', 'aws_key')
    # ### end Alembic commands ###
