"""empty message

Revision ID: a85058a4a8ae
Revises: 4268b3e24840
Create Date: 2019-10-18 14:55:03.581271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85058a4a8ae'
down_revision = '4268b3e24840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('scan_counter', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('xnat_label', sa.String(length=80), nullable=True))
    op.add_column('scan', sa.Column('xnat_label', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('experiment_counter', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('xnat_label', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('xnat_uri', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xnat_uri')
    op.drop_column('user', 'xnat_label')
    op.drop_column('user', 'experiment_counter')
    op.drop_column('scan', 'xnat_label')
    op.drop_column('experiment', 'xnat_label')
    op.drop_column('experiment', 'scan_counter')
    # ### end Alembic commands ###
