"""empty message

Revision ID: aebcd5639fed
Revises: ac610bb9de68
Create Date: 2018-11-25 18:41:18.736763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebcd5639fed'
down_revision = 'ac610bb9de68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('scan', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'created_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('experiments', 'created_at')
    # ### end Alembic commands ###
