"""empty message

Revision ID: c4273de5ecde
Revises: 4268b3e24840
Create Date: 2019-08-31 12:01:44.418491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4273de5ecde'
down_revision = '4268b3e24840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('xnat_uri', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'xnat_uri')
    # ### end Alembic commands ###
