"""empty message

Revision ID: e0b6b5bfb7b4
Revises: 96d8840955d3
Create Date: 2018-12-20 23:41:53.450593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b6b5bfb7b4'
down_revision = '96d8840955d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent_provided', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=30), nullable=True))
    #op.drop_column('user', 'username')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=True))
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('sex')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('dob')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('consent_provided')
    # ### end Alembic commands ###
