"""empty message

Revision ID: e0b6b5bfb7b4
Revises: 96d8840955d3
Create Date: 2018-12-20 23:41:53.450593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b6b5bfb7b4'
down_revision = '96d8840955d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consent_provided', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=30), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'sex')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'consent_provided')
    # ### end Alembic commands ###
