"""empty message

Revision ID: ebd409458a2c
Revises: a167f6258645
Create Date: 2019-12-16 17:58:43.394856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd409458a2c'
down_revision = 'a167f6258645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('label', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'label')
    # ### end Alembic commands ###
