"""empty message

Revision ID: 8148c8855508
Revises: 
Create Date: 2017-02-01 08:39:43.191704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8148c8855508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muser',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('sex', sa.String(length=35), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.String(length=35), nullable=True),
    sa.Column('is_author', sa.Boolean(), nullable=True),
    sa.Column('worker_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['Worker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('scan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('xnat_subject_id', sa.String(length=64), nullable=True),
    sa.Column('xnat_session_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('scan_number', sa.Integer(), nullable=True),
    sa.Column('scan_age', sa.Integer(), nullable=True),
    sa.Column('scan_date', sa.String(length=35), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['muser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Batch_study_id'), 'Batch', ['study_id'], unique=False)
    op.create_index(op.f('ix_BatchWorkerMap_worker_id'), 'BatchWorkerMap', ['worker_id'], unique=False)
    op.create_index(op.f('ix_Batch_allowedWorkerTypes_batch_id'), 'Batch_allowedWorkerTypes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_Component_study_id'), 'Component', ['study_id'], unique=False)
    op.create_index(op.f('ix_ComponentResult_component_id'), 'ComponentResult', ['component_id'], unique=False)
    op.create_index(op.f('ix_ComponentResult_studyResult_id'), 'ComponentResult', ['studyResult_id'], unique=False)
    op.create_index(op.f('ix_GroupResult_batch_id'), 'GroupResult', ['batch_id'], unique=False)
    op.create_index(op.f('ix_StudyResult_activeGroupMember_id'), 'StudyResult', ['activeGroupMember_id'], unique=False)
    op.create_index(op.f('ix_StudyResult_batch_id'), 'StudyResult', ['batch_id'], unique=False)
    op.create_index(op.f('ix_StudyResult_historyGroupMember_id'), 'StudyResult', ['historyGroupMember_id'], unique=False)
    op.create_index(op.f('ix_StudyResult_study_id'), 'StudyResult', ['study_id'], unique=False)
    op.create_index(op.f('ix_StudyResult_worker_id'), 'StudyResult', ['worker_id'], unique=False)
    op.create_index(op.f('ix_StudyUserMap_study_id'), 'StudyUserMap', ['study_id'], unique=False)
    op.create_index(op.f('ix_StudyUserMap_user_email'), 'StudyUserMap', ['user_email'], unique=False)
    op.create_index(op.f('ix_Worker_user_email'), 'Worker', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Worker_user_email'), table_name='Worker')
    op.drop_index(op.f('ix_StudyUserMap_user_email'), table_name='StudyUserMap')
    op.drop_index(op.f('ix_StudyUserMap_study_id'), table_name='StudyUserMap')
    op.drop_index(op.f('ix_StudyResult_worker_id'), table_name='StudyResult')
    op.drop_index(op.f('ix_StudyResult_study_id'), table_name='StudyResult')
    op.drop_index(op.f('ix_StudyResult_historyGroupMember_id'), table_name='StudyResult')
    op.drop_index(op.f('ix_StudyResult_batch_id'), table_name='StudyResult')
    op.drop_index(op.f('ix_StudyResult_activeGroupMember_id'), table_name='StudyResult')
    op.drop_index(op.f('ix_GroupResult_batch_id'), table_name='GroupResult')
    op.drop_index(op.f('ix_ComponentResult_studyResult_id'), table_name='ComponentResult')
    op.drop_index(op.f('ix_ComponentResult_component_id'), table_name='ComponentResult')
    op.drop_index(op.f('ix_Component_study_id'), table_name='Component')
    op.drop_index(op.f('ix_Batch_allowedWorkerTypes_batch_id'), table_name='Batch_allowedWorkerTypes')
    op.drop_index(op.f('ix_BatchWorkerMap_worker_id'), table_name='BatchWorkerMap')
    op.drop_index(op.f('ix_Batch_study_id'), table_name='Batch')
    op.drop_table('scan')
    op.drop_table('muser')
    # ### end Alembic commands ###
