"""empty message

Revision ID: 8bc10df956c9
Revises: 8148c8855508
Create Date: 2017-02-02 07:39:28.649205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bc10df956c9'
down_revision = '8148c8855508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('struct_mniSpace', sa.String(length=255), nullable=True))
    op.add_column('scan', sa.Column('struct_subjectSpace', sa.String(length=255), nullable=True))
    op.add_column('scan', sa.Column('upload_date', sa.DateTime(), nullable=True))
    op.add_column('scan', sa.Column('uploaded_file', sa.String(length=255), nullable=True))
    op.add_column('scan', sa.Column('zscore_mniSpace', sa.String(length=255), nullable=True))
    op.add_column('scan', sa.Column('zscore_subjectSpace', sa.String(length=255), nullable=True))
    op.drop_column('scan', 'image')
    op.drop_column('scan', 'publish_date')
    op.drop_column('scan', 'live')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('live', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('publish_date', mysql.DATETIME(), nullable=True))
    op.add_column('scan', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('scan', 'zscore_subjectSpace')
    op.drop_column('scan', 'zscore_mniSpace')
    op.drop_column('scan', 'uploaded_file')
    op.drop_column('scan', 'upload_date')
    op.drop_column('scan', 'struct_subjectSpace')
    op.drop_column('scan', 'struct_mniSpace')
    # ### end Alembic commands ###
