TEST:
  ENV: test
  DEBUG: False
  TESTING: True
  WTF_CSRF_ENABLED: False
  DEBUG_TB_ENABLED: False
  PRESERVE_CONTEXT_ON_EXCEPTION: False
  SECURITY_PASSWORD_SALT: not-so-secret-in-tests
  FULL_DB_URI: sqlite://

DOCKER:
  ENV: docker
  DEBUG: False
  SERVER_NAME: 0.0.0.0
  XNAT_HOST: https://mind-xnat.nyspi.org
  XNAT_DOCKER_HOST: http://10.20.193.32:2375
  DICOM_TO_NIFTI_COMMAND: 36
  FREESURFER_RECON_COMMAND: 37
  BROKER_URL: redis://redis:6379
  RESULTS_BACKEND: redis://redis:6379

STAGING:
  ENV: staging
  DEBUG: False
  SERVER_NAME: staging.mybrainandme.org
  PREFERRED_URL_SCHEME: https
  XNAT_HOST: https://mind-xnat.nyspi.org
  XNAT_DOCKER_HOST: http://10.20.193.32:2375
  XNAT_PROJECT: MBAM_STAGING
  DICOM_TO_NIFTI_COMMAND: 36
  FREESURFER_RECON_COMMAND: 37

TRUSTED:
  ENV: trusted
  SEMAPHORE_HASH_ID: ccb50d9e-4b65-4d19-9c9d-7a9cbe8f26d2
  CLOUDFRONT_URL:
  CFN_TEMPLATE_DIR: ../build/cfn
  CFN_TEMPLATE_BUCKET: s3://mbam-cfn-templates
  CFN_PROFILE: mbam
  AWS_DEFAULT_REGION: us-east-1
  FLASK_ENV: development
  FLASK_APP: autoapp.py
  FLASK_RUN_PORT: 8000
  FLASK_RUN_HOST: 0.0.0.0

LOCAL:
  ENV: local
  FLASK_APP: autoapp.py
  FLASK_ENV: development
  SECRET_KEY: 'not-so-secret'
  FLASK_RUN_PORT: 8000
  FLASK_RUN_HOST: 0.0.0.0





