TEST:
  ENV: test
  DEBUG: False
  TESTING: True
  WTF_CSRF_ENABLED: False
  DEBUG_TB_ENABLED: False
  PRESERVE_CONTEXT_ON_EXCEPTION: False
  SECRET_KEY: not-so-secret-in-tests
  SECURITY_PASSWORD_SALT: not-so-secret-in-tests
  STACK_NAME: staging
  IMAGE_REPO: mbam/flask-app
  AWS_DEFAULT_REGION : us-east-1
  AWS_ACCOUNT_ID : 413377292493
  MIND_DICOM_TO_NIFTI_COMMAND: 36
  MIND_FREESURFER_RECON_COMMAND: 37
  MIND_XNAT_PROJECT: MBAM_TEST
  MIND_XNAT_HOST: https://mind-xnat.nyspi.org
  MAIL_USERNAME: foo
  MAIL_PASSWORD: bar
  CLOUDFRONT_URL: baz
  CLOUDFRONT_KEY_ID: foo
  CLOUDFRONT_SECRET_KEY: bar
  S3_KEY_ID: baz
  S3_SECRET_KEY: foo
  FLASK_ENV: test
  FLASK_APP: ../autoapp.py
  SQLITE_URI: sqlite:////tmp/dev.db
  MYSQL_USER: mbam
  MYSQL_LOCAL_HOST: localhost
  MYSQL_DOCKER_HOST: mysql
  MYSQL_PASSWORD: mbam123

DOCKER:
  ENV: docker
  DEBUG: False
  SERVER_NAME: 0.0.0.0
  FLASK_RUN_PORT: 8000
  FLASK_APP: autoapp.py
  FLASK_ENV: production
  FLASK_RUN_HOST: 0.0.0.0
  MIND_XNAT_HOST: https://mind-xnat.nyspi.org
  MIND_DICOM_TO_NIFTI_COMMAND: 36
  MIND_FREESURFER_RECON_COMMAND: 37
  MIND_DOCKER_HOST: http://10.20.193.32:2375
  MIND_XNAT_PROJECT: MBAM_TEST
  MIND_XNAT_DOCKER_HOST: http://10.20.193.32:2375
  BROKER_URL: redis://redis:6379
  RESULTS_BACKEND: redis://redis:6379
  MYSQL_USER: mbam
  MYSQL_DOCKER_HOST: mysql
  MYSQL_LOCAL_HOST: localhost
  MYSQL_PASSWORD: mbam123
  SQLITE_URI: sqlite:////tmp/dev.db
  AWS_DEFAULT_REGION: us-east-1
  CLOUDFRONT_URL: https://dc2khv0msnx9b.cloudfront.net/
  S3_BUCKET: 'mbam-test-sp'

STAGING:
  ENV: staging
  DEBUG: False
  SERVER_NAME: staging.mybrainandme.org
  PREFERRED_URL_SCHEME: https
  FLASK_APP: autoapp.py
  FLASK_ENV: production
  BASIC_AUTH_FORCE: True
  MIND_XNAT_HOST: https://mind-xnat.nyspi.org
  MIND_DICOM_TO_NIFTI_COMMAND: 36
  MIND_FREESURFER_RECON_COMMAND: 37
  MIND_FS_TO_MESH_COMMAND: 39
  MIND_XNAT_DOCKER_HOST: http://10.20.193.32:2375
  MIND_XNAT_PROJECT: MBAM_STAGING
  AWS_ACCOUNT_ID: 413377292493
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_REPO: mbam/flask-app
  STACK_NAME: staging
  MAIL_SERVER: email-smtp.us-east-1.amazonaws.com
  SECURITY_EMAIL_SENDER: '"My Brain and Me" <info@mybrainandme.org>'
  MYSQL_HOST: braindb-instance.clem3xtlzpyq.us-east-1.rds.amazonaws.com
  JATOS_DB_URL: jdbc:mysql://braindb-instance.clem3xtlzpyq.us-east-1.rds.amazonaws.com/brain_db?characterEncoding=UTF-8&useSSL=false
  S3_BUCKET: 'mbam-test-sp'

QA:
  ENV: qa
  DEBUG: False
  SERVER_NAME: qa.mybrainandme.org
  PREFERRED_URL_SCHEME: https
  FLASK_APP: autoapp.py
  FLASK_ENV: production
  BASIC_AUTH_FORCE: True
  MIND_XNAT_HOST: https://mind-xnat.nyspi.org
  MIND_DICOM_TO_NIFTI_COMMAND: 36
  MIND_FREESURFER_RECON_COMMAND: 37
  MIND_FS_TO_MESH_COMMAND: 39
  MIND_XNAT_DOCKER_HOST: http://10.20.193.32:2375
  MIND_XNAT_PROJECT: MBAM_QA
  AWS_ACCOUNT_ID: 413377292493
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_REPO: mbam/flask-app
  STACK_NAME: qa
  MAIL_SERVER: email-smtp.us-east-1.amazonaws.com
  SECURITY_EMAIL_SENDER: '"My Brain and Me" <info@mybrainandme.org>'
  MYSQL_HOST: braindb-instance.clem3xtlzpyq.us-east-1.rds.amazonaws.com
  JATOS_DB_URL: jdbc:mysql://braindb-instance.clem3xtlzpyq.us-east-1.rds.amazonaws.com/brain_db?characterEncoding=UTF-8&useSSL=false
  S3_BUCKET: 'mbam-test-sp'

TRUSTED:
  ENV: trusted
  TESTING: False
  DEBUG: True
  SEMAPHORE_HASH_ID: ccb50d9e-4b65-4d19-9c9d-7a9cbe8f26d2
  CLOUDFRONT_URL: https://dc2khv0msnx9b.cloudfront.net/
  CFN_TEMPLATE_DIR: ../../build/cfn
  CFN_TEMPLATE_BUCKET: s3://mbam-cfn-templates
  CFN_PROFILE: mbam
  MIND_XNAT_HOST: https://mind-xnat.nyspi.org
  MIND_XNAT_PROJECT: MBAM_TEST
  MIND_DICOM_TO_NIFTI_COMMAND: 36
  #MIND_FREESURFER_RECON_COMMAND: 40 # MOCK FREESURFER
  MIND_FREESURFER_RECON_COMMAND: 37
  MIND_FS_TO_MESH_COMMAND: 39
  BACKUP_XNAT_HOST: http://10.20.205.246:8080
  BACKUP_XNAT_PROJECT: MBAM_TEST
  BACKUP_DICOM_TO_NIFTI_COMMAND: 6
  BACKUP_FREESURFER_RECON_COMMAND: 9 # MOCK FREESURFER
  #BACKUP_FREESURFER_RECON_COMMAND: 7
  BACKUP_FS_TO_MESH_COMMAND: 10
  AWS_DEFAULT_REGION: us-east-1
  FLASK_ENV: development
  FLASK_APP: autoapp.py
  FLASK_RUN_PORT: 8000
  FLASK_RUN_HOST: 0.0.0.0
  SQLITE_URI: sqlite:////tmp/dev.db
  MYSQL_USER: mbam
  MYSQL_LOCAL_HOST: localhost
  MYSQL_DOCKER_HOST: mysql
  MYSQL_PASSWORD: mbam123


LOCAL:
  ENV: local
  DEBUG: True
  FLASK_ENV: development
  FLASK_APP: autoapp.py
  SECRET_KEY: not-so-secret
  FLASK_RUN_PORT: 8000
  FLASK_RUN_HOST: 0.0.0.0
  SECURITY_PASSWORD_SALT: not_so_secret_salt
  SQLITE_URI: sqlite:////tmp/dev.db
  MYSQL_USER: mbam
  MYSQL_LOCAL_HOST: localhost
  MYSQL_DOCKER_HOST: mysql
  MYSQL_PASSWORD: mbam123
  VVM_XNAT_HOST: http://10.1.1.17/
  VVM_DICOM_TO_NIFTI_COMMAND: 1
  VVM_FREESURFER_RECON_COMMAND: 2
  VVM_XNAT_PASSWORD: admin
  VVM_XNAT_USER: admin
