#FROM mysql:latest
FROM mysql:5.7.19
#FROM mariadb:latest

# Here set enviromental variables
#ENV MYSQL_DATABASE  brain_db
#ENV MYSQL_ROOT_PASSWORD test
#ENV MYSQL_USER  mbam
#ENV MYSQL_PASSWORD ''
#ENV MYSQL_ALLOW_EMPTY_PASSWORD Tru
